import { RawCaliberType } from "../types";

export const CaliberDefaults: RawCaliberType[] = [
  { caliber: ".260 Caliber", description: ".260 Caliber", conversion: [] },
  { caliber: ".40 Caliber", description: ".40 Caliber", conversion: [] },
  { caliber: ".45 Caliber", description: ".45 Caliber", conversion: [] },
  { caliber: ".50 Caliber", description: ".50 Caliber", conversion: [] },
  { caliber: "10 Gauge", description: "10 Gauge", conversion: [] },
  { caliber: "10mm", description: "10mm", conversion: [] },
  {
    caliber: "10MM | 40 S&amp;W",
    description: "10MM | 40 S&amp;W",
    conversion: [],
  },
  { caliber: "12 Gauge", description: "12 Gauge", conversion: [] },
  {
    caliber: "12 Gauge | 20 Gauge",
    description: "12 Gauge | 20 Gauge",
    conversion: [],
  },
  {
    caliber: "12 Gauge | 22 LR",
    description: "12 Gauge | 22 LR",
    conversion: [],
  },
  {
    caliber: "12 Gauge | 22 Magnum",
    description: "12 Gauge | 22 Magnum",
    conversion: [],
  },
  { caliber: "16 Gauge", description: "16 Gauge", conversion: [] },
  { caliber: "17 HM2", description: "17 HM2", conversion: [] },
  { caliber: "17 HM2 | 22 LR", description: "17 HM2 | 22 LR", conversion: [] },
  { caliber: "17 HMR", description: "17 HMR", conversion: [] },
  {
    caliber: "17 HMR | 22 Magnum",
    description: "17 HMR | 22 Magnum",
    conversion: [],
  },
  { caliber: "17 Hornet", description: "17 Hornet", conversion: [] },
  { caliber: "17 WSM", description: "17 WSM", conversion: [] },
  { caliber: "20 Gauge", description: "20 Gauge", conversion: [] },
  {
    caliber: "20 Gauge | 22 LR",
    description: "20 Gauge | 22 LR",
    conversion: [],
  },
  { caliber: "204 Ruger", description: "204 Ruger", conversion: [] },
  { caliber: "22 Hornet", description: "22 Hornet", conversion: [] },
  { caliber: "22 LR", description: "22 LR", conversion: [] },
  { caliber: "22 LR | 17 HMR", description: "22 LR | 17 HMR", conversion: [] },
  {
    caliber: "22 LR | 22 Magnum",
    description: "22 LR | 22 Magnum",
    conversion: [],
  },
  { caliber: "22 LR | 45 ACP", description: "22 LR | 45 ACP", conversion: [] },
  { caliber: "22 Magnum", description: "22 Magnum", conversion: [] },
  { caliber: "22 NOSLER", description: "22 NOSLER", conversion: [] },
  { caliber: "22 REV", description: "22 REV", conversion: [] },
  { caliber: "22 Short", description: "22 Short", conversion: [] },
  { caliber: "22 TCM", description: "22 TCM", conversion: [] },
  { caliber: "222 Rem", description: "222 Rem", conversion: [] },
  { caliber: "22-250", description: "22-250", conversion: [] },
  { caliber: "223 Rem", description: "223 Rem", conversion: [] },
  {
    caliber: "223 Rem | 5.56 NATO",
    description: "223 Rem | 5.56 NATO",
    conversion: [],
  },
  { caliber: "223 Wylde", description: "223 Wylde", conversion: [] },
  { caliber: "224 VALKYRIE", description: "224 VALKYRIE", conversion: [] },
  { caliber: "240 WBY Mag", description: "240 WBY Mag", conversion: [] },
  { caliber: "243 Win", description: "243 Win", conversion: [] },
  { caliber: "25 ACP", description: "25 ACP", conversion: [] },
  { caliber: "25 NAA", description: "25 NAA", conversion: [] },
  { caliber: "25-06", description: "25-06", conversion: [] },
  { caliber: "257 WBY Mag", description: "257 WBY Mag", conversion: [] },
  { caliber: "26 Nosler", description: "26 Nosler", conversion: [] },
  { caliber: "260 Rem", description: "260 Rem", conversion: [] },
  { caliber: "264 Win", description: "264 Win", conversion: [] },
  { caliber: "270 WBY Mag", description: "270 WBY Mag", conversion: [] },
  { caliber: "270 Win", description: "270 Win", conversion: [] },
  { caliber: "270 WSM", description: "270 WSM", conversion: [] },
  { caliber: "275 Rigby", description: "275 Rigby", conversion: [] },
  { caliber: "277 FURY", description: "277 FURY", conversion: [] },
  { caliber: "28 Gauge", description: "28 Gauge", conversion: [] },
  { caliber: "28 Nosler", description: "28 Nosler", conversion: [] },
  { caliber: "280 ACKLY", description: "280 ACKLY", conversion: [] },
  { caliber: "280 Rem", description: "280 Rem", conversion: [] },
  {
    caliber: "30 Caliber | 7.62mm",
    description: "30 Caliber | 7.62mm",
    conversion: [],
  },
  { caliber: "30 Carbine", description: "30 Carbine", conversion: [] },
  { caliber: "30 Nosler", description: "30 Nosler", conversion: [] },
  {
    caliber: "300 AAC Blackout",
    description: "300 AAC Blackout",
    conversion: [],
  },
  {
    caliber: "300 Norma Magnum",
    description: "300 Norma Magnum",
    conversion: [],
  },
  { caliber: "300 PRC", description: "300 PRC", conversion: [] },
  {
    caliber: "300 Rem Ultra Mag",
    description: "300 Rem Ultra Mag",
    conversion: [],
  },
  { caliber: "300 WBY Mag", description: "300 WBY Mag", conversion: [] },
  {
    caliber: "300 Whisper | 300 AAC Blackout",
    description: "300 Whisper | 300 AAC Blackout",
    conversion: [],
  },
  { caliber: "300 Win Mag", description: "300 Win Mag", conversion: [] },
  { caliber: "300 WSM", description: "300 WSM", conversion: [] },
  { caliber: "30-06", description: "30-06", conversion: [] },
  { caliber: "30-30", description: "30-30", conversion: [] },
  { caliber: "30-378 WBY Mag", description: "30-378 WBY Mag", conversion: [] },
  { caliber: "30-40 Krag", description: "30-40 Krag", conversion: [] },
  { caliber: "308 Win", description: "308 Win", conversion: [] },
  {
    caliber: "308 Win | 338 Lapua",
    description: "308 Win | 338 Lapua",
    conversion: [],
  },
  { caliber: "32 ACP", description: "32 ACP", conversion: [] },
  { caliber: "32 H&amp;R Mag", description: "32 H&amp;R Mag", conversion: [] },
  {
    caliber: "327 Federal Magnum",
    description: "327 Federal Magnum",
    conversion: [],
  },
  { caliber: "33 NOSLER", description: "33 NOSLER", conversion: [] },
  { caliber: "338 Lapua", description: "338 Lapua", conversion: [] },
  {
    caliber: "338 LAPUA | 378 WBY",
    description: "338 LAPUA | 378 WBY",
    conversion: [],
  },
  { caliber: "338 Win Mag", description: "338 Win Mag", conversion: [] },
  {
    caliber: "338-378 WBY Mag",
    description: "338-378 WBY Mag",
    conversion: [],
  },
  { caliber: "35 Rem", description: "35 Rem", conversion: [] },
  { caliber: "35 Whelen", description: "35 Whelen", conversion: [] },
  { caliber: "350 Legend", description: "350 Legend", conversion: [] },
  { caliber: "357 Magnum", description: "357 Magnum", conversion: [] },
  {
    caliber: "357 Magnum | 38 Special",
    description: "357 Magnum | 38 Special",
    conversion: [],
  },
  {
    caliber: "357 Magnum | 38 Special | 9mm",
    description: "357 Magnum | 38 Special | 9mm",
    conversion: [],
  },
  {
    caliber: "357 Magnum | 9mm",
    description: "357 Magnum | 9mm",
    conversion: [],
  },
  { caliber: "357 Sig", description: "357 Sig", conversion: [] },
  { caliber: "358 Win", description: "358 Win", conversion: [] },
  { caliber: "375 H&amp;H", description: "375 H&amp;H", conversion: [] },
  { caliber: "375 Ruger", description: "375 Ruger", conversion: [] },
  { caliber: "38 Special", description: "38 Special", conversion: [] },
  { caliber: "38 Super", description: "38 Super", conversion: [] },
  { caliber: "380 ACP", description: "380 ACP", conversion: [] },
  { caliber: "38-55 Win", description: "38-55 Win", conversion: [] },
  { caliber: "40 S&amp;W", description: "40 S&amp;W", conversion: [] },
  { caliber: "405 Win", description: "405 Win", conversion: [] },
  { caliber: "41 Magnum", description: "41 Magnum", conversion: [] },
  { caliber: "410 Bore", description: "410 Bore", conversion: [] },
  {
    caliber: "410 Bore | 22 LR",
    description: "410 Bore | 22 LR",
    conversion: [],
  },
  {
    caliber: "410 Bore | 22 Magnum",
    description: "410 Bore | 22 Magnum",
    conversion: [],
  },
  {
    caliber: "410 Bore | 243 Win",
    description: "410 Bore | 243 Win",
    conversion: [],
  },
  {
    caliber: "410 Bore | 45 Colt",
    description: "410 Bore | 45 Colt",
    conversion: [],
  },
  {
    caliber: "410 Bore | 45 Colt | 45 ACP",
    description: "410 Bore | 45 Colt | 45 ACP",
    conversion: [],
  },
  { caliber: "416 Barrett", description: "416 Barrett", conversion: [] },
  { caliber: "416 Ruger", description: "416 Ruger", conversion: [] },
  { caliber: "429 DE", description: "429 DE", conversion: [] },
  { caliber: "44 Magnum", description: "44 Magnum", conversion: [] },
  {
    caliber: "44 Magnum | 44 Special",
    description: "44 Magnum | 44 Special",
    conversion: [],
  },
  {
    caliber: "44 Magnum | 50 A.E.",
    description: "44 Magnum | 50 A.E.",
    conversion: [],
  },
  { caliber: "44 Special", description: "44 Special", conversion: [] },
  { caliber: "444 Marlin", description: "444 Marlin", conversion: [] },
  { caliber: "44-40", description: "44-40", conversion: [] },
  { caliber: "45 ACP", description: "45 ACP", conversion: [] },
  {
    caliber: "45 ACP | 45 Colt",
    description: "45 ACP | 45 Colt",
    conversion: [],
  },
  { caliber: "45 Caliber", description: "45 Caliber", conversion: [] },
  { caliber: "45 Colt", description: "45 Colt", conversion: [] },
  { caliber: "45 GAP", description: "45 GAP", conversion: [] },
  { caliber: "450 Bushmaster", description: "450 Bushmaster", conversion: [] },
  { caliber: "450 Marlin", description: "450 Marlin", conversion: [] },
  { caliber: "454 Casull", description: "454 Casull", conversion: [] },
  { caliber: "45-70 GOVT", description: "45-70 GOVT", conversion: [] },
  { caliber: "45-90", description: "45-90", conversion: [] },
  { caliber: "46 Caliber", description: "46 Caliber", conversion: [] },
  {
    caliber: "460 S&amp;W Magnum",
    description: "460 S&amp;W Magnum",
    conversion: [],
  },
  {
    caliber: "475 Linebaugh | 480 Ruger",
    description: "475 Linebaugh | 480 Ruger",
    conversion: [],
  },
  { caliber: "480 Ruger", description: "480 Ruger", conversion: [] },
  { caliber: "5.45 x 39mm", description: "5.45 x 39mm", conversion: [] },
  { caliber: "5.56 x 45mm", description: "5.56 x 45mm", conversion: [] },
  { caliber: "5.7 x 28mm", description: "5.7 x 28mm", conversion: [] },
  { caliber: "50 AE", description: "50 AE", conversion: [] },
  { caliber: "50 BMG", description: "50 BMG", conversion: [] },
  { caliber: "50 Caliber", description: "50 Caliber", conversion: [] },
  { caliber: "500 JRH", description: "500 JRH", conversion: [] },
  { caliber: "500 Linebaugh", description: "500 Linebaugh", conversion: [] },
  {
    caliber: "500 S&amp;W Magnum",
    description: "500 S&amp;W Magnum",
    conversion: [],
  },
  { caliber: "6.5 Creedmoor", description: "6.5 Creedmoor", conversion: [] },
  { caliber: "6.5 Grendel", description: "6.5 Grendel", conversion: [] },
  { caliber: "6.5 PRC", description: "6.5 PRC", conversion: [] },
  { caliber: "6.5 WBY RPM", description: "6.5 WBY RPM", conversion: [] },
  {
    caliber: "6.5 x 284 Norma",
    description: "6.5 x 284 Norma",
    conversion: [],
  },
  {
    caliber: "6.5 x 55 Swedish",
    description: "6.5 x 55 Swedish",
    conversion: [],
  },
  { caliber: "6.5 x 55mm", description: "6.5 x 55mm", conversion: [] },
  {
    caliber: "6.5-300 WBY Mag",
    description: "6.5-300 WBY Mag",
    conversion: [],
  },
  { caliber: "6.8 Western", description: "6.8 Western", conversion: [] },
  { caliber: "6.8mm SPC", description: "6.8mm SPC", conversion: [] },
  { caliber: "6MM ARC", description: "6MM ARC", conversion: [] },
  { caliber: "6mm Creedmoor", description: "6mm Creedmoor", conversion: [] },
  { caliber: "7.62 x 25mm", description: "7.62 x 25mm", conversion: [] },
  { caliber: "7.62 x 39mm", description: "7.62 x 39mm", conversion: [] },
  {
    caliber: "7.62 x 51mm | 308 Win",
    description: "7.62 x 51mm | 308 Win",
    conversion: [],
  },
  { caliber: "7.62 x 54r", description: "7.62 x 54r", conversion: [] },
  { caliber: "7mm Rem Mag", description: "7mm Rem Mag", conversion: [] },
  { caliber: "7mm WBY Mag", description: "7mm WBY Mag", conversion: [] },
  { caliber: "7mm-08", description: "7mm-08", conversion: [] },
  { caliber: "9mm", description: "9mm", conversion: [] },
  { caliber: "9mm | 22 TCM", description: "9mm | 22 TCM", conversion: [] },
  { caliber: "Multi", description: "Multi", conversion: [] },
];
