import { RawManufacturerType } from "../types";

export const ManufacturerDefaults: RawManufacturerType[] = [
  {
    manufacturer: "American Classic",
    description: "American Classic",
    conversion: [],
  },
  {
    manufacturer: "American Tactical Inc",
    description: "American Tactical Inc",
    conversion: [ "ATI", "American Tactical"],
  },
  { manufacturer: "ATN", description: "ATN", conversion: [] },
  {
    manufacturer: "Auto-Ordnance",
    description: "Auto-Ordnance - Thompson",
    conversion: [ "Auto-Ordnance"],
  },
  {
    manufacturer: "Barrett Firearms",
    description: "Barrett Firearms",
    conversion: ["Barrett"],
  },
  { manufacturer: "Beretta", description: "Beretta", conversion: [] },
  { manufacturer: "Bergara", description: "Bergara", conversion: [] },
  { manufacturer: "Bersa", description: "Bersa", conversion: [] },
  { manufacturer: "BLACKHAWK!", description: "BLACKHAWK!", conversion: ["BLACKHAWK"] },
  { manufacturer: "Bond Arms", description: "Bond Arms", conversion: [] },
  { manufacturer: "Browning", description: "Browning", conversion: [] },
  {
    manufacturer: "Burris Optics",
    description: "Burris Optics",
    conversion: ["Burris"],
  },
  { manufacturer: "Bushnell", description: "Bushnell", conversion: [] },
  {
    manufacturer: "Byrna Technologies",
    description: "Byrna Technologies",
    conversion: [],
  },
  { manufacturer: "CANIK", description: "CANIK", conversion: [] },
  { manufacturer: "Century Arms", description: "Century Arms", conversion: [] },
  { manufacturer: "CGS Group", description: "CGS Group", conversion: [] },
  { manufacturer: "Charles Daly", description: "Charles Daly", conversion: [] },
  { manufacturer: "Charter Arms", description: "Charter Arms", conversion: [] },
  {
    manufacturer: "Chiappa Firearms",
    description: "Chiappa Firearms",
    conversion: ["Chiappa"],
  },
  {
    manufacturer: "Christensen Arms",
    description: "Christensen Arms",
    conversion: [],
  },
  { manufacturer: "Colt", description: "Colt", conversion: [] },
  { manufacturer: "Comanche", description: "Comanche", conversion: [] },
  {
    manufacturer: "Crimson Trace",
    description: "Crimson Trace",
    conversion: [],
  },
  { manufacturer: "CVA", description: "CVA", conversion: [] },
  { manufacturer: "CZ-USA", description: "CZ-USA", conversion: [] },
  {
    manufacturer: "Daniel Defense",
    description: "Daniel Defense",
    conversion: ["DD"],
  },
  {
    manufacturer: "Dead Air Armament",
    description: "Dead Air Armament",
    conversion: ["Dead Air"],
  },
  { manufacturer: "Del-Ton", description: "Del-Ton", conversion: [] },
  {
    manufacturer: "Diamondback Firearms",
    description: "Diamondback Firearms",
    conversion: ["Diamondback"],
  },
  { manufacturer: "EO Tech", description: "EO Tech", conversion: [] },
  { manufacturer: "FN", description: "FN", conversion: ["FNH"] },
  { manufacturer: "Four Peaks", description: "Four Peaks", conversion: [] },
  {
    manufacturer: "Franklin Armory",
    description: "Franklin Armory",
    conversion: [],
  },
  { manufacturer: "Gemtech", description: "Gemtech", conversion: [] },
  { manufacturer: "GLOCK", description: "GLOCK", conversion: [] },
  {
    manufacturer: "Heckler and Koch",
    description: "Heckler and Koch (HK USA)",
    conversion: ["HK"],
  },
  {
    manufacturer: "Henry Repeating Arms",
    description: "Henry Repeating Arms",
    conversion: ["Henry"],
  },
  {
    manufacturer: "Heritage Manufacturing",
    description: "Heritage Manufacturing",
    conversion: ["Heritage"],
  },
  { manufacturer: "Hi-Point", description: "Hi-Point", conversion: [] },
  { manufacturer: "HOWA", description: "HOWA", conversion: [] },
  {
    manufacturer: "Inland Manufacturing",
    description: "Inland Manufacturing",
    conversion: [],
  },
  {
    manufacturer: "IWI - Israel Weapon Industries",
    description: "IWI - Israel Weapon Industries",
    conversion: ["IWI", "Israel Weapon Industries"],
  },
  { manufacturer: "Kahr Arms", description: "Kahr Arms", conversion: [] },
  { manufacturer: "Keltec", description: "Keltec", conversion: [] },
  {
    manufacturer: "Keystone Sporting Arms",
    description: "Keystone Sporting Arms",
    conversion: ["Keystone"],
  },
  { manufacturer: "Kriss USA", description: "Kriss USA", conversion: ["Kriss"] },
  {
    manufacturer: "Legacy Sports International",
    description: "Legacy Sports International",
    conversion: [],
  },
  { manufacturer: "Leupold", description: "Leupold", conversion: [] },
  { manufacturer: "LWRC", description: "LWRC", conversion: [] },
  {
    manufacturer: "Magnum Research",
    description: "Magnum Research",
    conversion: [],
  },
  { manufacturer: "Mossberg", description: "Mossberg", conversion: [] },
  {
    manufacturer: "North American Arms",
    description: "North American Arms",
    conversion: ["NAA"],
  },
  { manufacturer: "POF USA", description: "POF USA", conversion: ["POF"] },
  { manufacturer: "Pointer", description: "Pointer", conversion: [] },
  { manufacturer: "ProMag", description: "ProMag", conversion: [] },
  { manufacturer: "Q", description: "Q", conversion: [] },
  { manufacturer: "Redfield", description: "Redfield", conversion: [] },
  { manufacturer: "Remington", description: "Remington", conversion: [] },
  { manufacturer: "Riton Optics", description: "Riton Optics", conversion: [] },
  {
    manufacturer: "Rock Island Armory",
    description: "Rock Island Armory",
    conversion: [],
  },
  { manufacturer: "Rossi", description: "Rossi", conversion: [] },
  { manufacturer: "Ruger", description: "Ruger", conversion: [] },
  {
    manufacturer: "Rugged Suppressors",
    description: "Rugged Suppressors",
    conversion: [],
  },
  { manufacturer: "Savage Arms", description: "Savage Arms", conversion: [] },
  {
    manufacturer: "SCCY Industries",
    description: "SCCY Industries",
    conversion: ["SCCY"],
  },
  { manufacturer: "SIG SAUER", description: "SIG SAUER", conversion: [] },
  {
    manufacturer: "Sig Sauer Germany",
    description: "Sig Sauer Germany",
    conversion: ["Sig Sauer", "Sig"],
  },
  { manufacturer: "SilencerCo", description: "SilencerCo", conversion: [] },
  {
    manufacturer: "Simmons Optics",
    description: "Simmons Optics",
    conversion: [],
  },
  {
    manufacturer: "Smith and Wesson",
    description: "Smith and Wesson",
    conversion: ["Smith & Wesson"],
  },
  {
    manufacturer: "Springfield Armory",
    description: "Springfield Armory",
    conversion: [],
  },
  { manufacturer: "SureFire", description: "SureFire", conversion: [] },
  { manufacturer: "Tasco", description: "Tasco", conversion: [] },
  { manufacturer: "Taurus", description: "Taurus", conversion: [] },
  {
    manufacturer: "Thompson Center",
    description: "Thompson Center",
    conversion: [],
  },
  { manufacturer: "Tikka", description: "Tikka", conversion: [] },
  {
    manufacturer: "Toolman Tactical",
    description: "Toolman Tactical",
    conversion: [],
  },
  { manufacturer: "Traditions", description: "Traditions", conversion: [] },
  { manufacturer: "Trijicon", description: "Trijicon", conversion: [] },
  {
    manufacturer: "TriStar Sporting Arms",
    description: "TriStar Sporting Arms",
    conversion: [],
  },
  { manufacturer: "Walther Arms", description: "Walther Arms", conversion: ["Walther"] },
  { manufacturer: "Warne", description: "Warne", conversion: [] },
  { manufacturer: "Weatherby", description: "Weatherby", conversion: [] },
  { manufacturer: "Weaver", description: "Weaver", conversion: [] },
  { manufacturer: "Winchester", description: "Winchester", conversion: [] },
  {
    manufacturer: "Windham Weaponry",
    description: "Windham Weaponry",
    conversion: [],
  },
  {
    manufacturer: "Yankee Hill Machine Company",
    description: "Yankee Hill Machine Company",
    conversion: ["YHM"],
  },
  {
    manufacturer: "Zastava Arms USA",
    description: "Zastava Arms USA",
    conversion: ["Zastava"],
  },
  {
    manufacturer: "ZEV TECHNOLOGIES",
    description: "ZEV TECHNOLOGIES",
    conversion: ["ZEV"],
  },
];
